### ISSUE TITLE
Conflict with MassiveCore

### ISSUE THREAD

**Issue by IsmaelHG** [nitnelave/CreeperHeal#34]
Hello,

I can't load MassiveCore if I have the plugin creeperheal.
Error:
org.bukkit.plugin.InvalidPluginException: java.lang.IllegalArgumentException: Plugin already initialized!

Detailed error:
http://pastebin.com/Uu2Bahx7

Version Spigot: 1.10.2
Version CreeperHeal: 7.0.0.1
Version MassiveCore: 2.9.0

**Comment by DaDMaR** [comment]
DaDMar777  (from Spigot disscussion)
Got a problem - two plugins not playing well together - see link - both work without each other.
Massivecore and Creeperheal ----dont make me choose.........sob.......cry.......
http://pastebin.com/mJQPHWmF
-------------------------------------------------------------------------------------------------------------
jikoo
For some reason, @nitnelave shaded all the plugins CreeperHeal depends on into the final file.
------------------------------------------------------------------------------------------------------------
DaDMaR777
I can't program - not a coder - but opened jar file - deleted excess -
Massive core files - and other stuff
Well my surprise - is co-habiting with MassiveCore now - and appears to be working :D

:eek: -- WARNING USE A YOUR OWN RISK-- :eek:

thanks jikoo for observation
https://www.dropbox.com/s/3d2gs1mjz7t41jq/CreeperHeal-7.0.1_1.11.shrunk.jar?dl=0
https://www.dropbox.com/s/mwyvvccjjs96j5g/CreeperHeal-7.0.1_1.11.shrunk .jar.-rename?dl=0
------------------------------------------------------------------------------------------------------------
DaDMaR (now)
Since above have deleted more files found included in the jar file
file size now reduced to v7.0.1shrunk=167kb - from 3600kb=v7.0.1original size - NOTE v6.8.5=166kb only

**Comment by nitnelave** [comment]
Should be fixed with 7.0.2. Re-open if not.
