### ISSUE TITLE
Beds in nether not exploding consistently

### ISSUE THREAD

**Issue by gamma-02** [nitnelave/CreeperHeal#68]
Even after we Uninstalled the plugin, beds do not consistently explode in the nether

**Comment by nitnelave** [comment]
Hi,

If you uninstalled the plugin and restarted the server, then it can't be because of the plugin :) It has no code left running, and it doesn't affect permanent server settings.

**Comment by gamma-02** [comment]
yes, I know. I am a Java programer. However, the issues only started AFTER we uninstalled the plugin.

**Comment by nitnelave** [comment]
If you're a Java programmer, then you'll know that there's not much I can do to help you if you already uninstalled the plugin :)
Did you check the server startup log to see if CreeperHeal loaded? If there's no CreeperHeal loading message, then it *can't* be due to the plugin, and is most likely due to something else in your configuration: another plugin, some config change, ...

**Comment by gamma-02** [comment]
ok, that's true...
